### ISSUE TITLE
BUG - SecLists Doesn't Clone

### ISSUE THREAD

**Issue by 0xdf-0xdf** [fireeye/commando-vm#38]
**Describe the bug and expected behavior**
SecLists is included in the software to be included. However, after install it doesn't show up in the wordlists shortcuts, in tools, or as something checked when running `cup`.

I tried to clone it myself, and it gives a partial copy, with a lot of errors (due to the types of files in SecLists?). Could these errors be why it didn't install in the first place?

**To Reproduce**
Try to locate SecLists.

Try to clone seclists.

**Example**
```
C:\Tools>git clone https://github.com/danielmiessler/SecLists.git
Cloning into 'SecLists'...
remote: Enumerating objects: 47, done.
remote: Counting objects: 100% (47/47), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 7765 (delta 23), reused 34 (delta 16), pack-reused 7718
Receiving objects: 100% (7765/7765), 455.42 MiB | 24.08 MiB/s, done.
Resolving deltas: 100% (3835/3835), done.
error: invalid path 'Payloads/File-Names/traversal/..\:;'
error: unable to create file Payloads/File-Names/max-length/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA: Filename too long
error: unable to create file Payloads/File-Names/max-length/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.php.gif: Filename too long
error: unable to create file Payloads/File-Names/traversal/..::..::;: Invalid argument
error: unable to create file Payloads/File-Names/traversal/..::;: Invalid argument
error: unable to create file Payloads/File-Names/traversal/..:;: Invalid argument
error: unable to create file Payloads/File-Names/traversal/..;:: Invalid argument
error: unable to create file Payloads/File-Names/traversal/.:..:: Invalid argument
error: unable to create file Payloads/File-Names/traversal/.:..:;: Invalid argument
error: unable to create file Payloads/File-Names/traversal/.:;: Invalid argument
error: unable to create file Payloads/File-Names/traversal/.;:: Invalid argument
error: unable to create file Payloads/File-Names/traversal/:..:;: Invalid argument
error: unable to create file Payloads/File-Names/traversal/::..::;: Invalid argument
error: unable to create file Payloads/File-Names/traversal/:;: Invalid argument
error: unable to create file Payloads/File-Names/traversal/;:: Invalid argument
error: unable to create file Payloads/File-Names/traversal/;\:: Invalid argument
Checking out files: 100% (5215/5215), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

**Version**
 - OS: Win10

**Comment by day1player** [comment]
@0xdf-0xdf we noticed this when we first started installing seclists onto Commando. What is happening is the filename directory traversal payloads are actually being executed as the package is being decompressed. SecLists is installed by Commando by default, and you should be able to locate in either in your desktop folder, under Wordlists, or in the C:\Tools directory. If you can not find it, it may not have installed, and you should be able to run `cinst -s https://www.myget.org/F/fireeye/api/v2 -f seclists.fireeye` to install it again.

We remove the filename directory traversal portion of the zip before decompressing which allows it to be installed properly (if not completely) onto the system.

**Comment by day1player** [comment]
Discovered that seclists.fireeye was not in the packages.json file. fixed now.

**Comment by 0xdf-0xdf** [comment]
Yup, I had tried that, but it didn't work. Can confirm it does work now. Thanks!

**Comment by bkoprivica** [comment]
the bug is still there:

>git clone https://github.com/danielmiessler/SecLists.git
Cloning into 'SecLists'...
remote: Enumerating objects: 11021, done.
remote: Total 11021 (delta 0), reused 0 (delta 0), pack-reused 11021
Receiving objects: 100% (11021/11021), 834.50 MiB | 1.15 MiB/s, done.
Resolving deltas: 100% (5941/5941), done.
error: invalid path 'Payloads/File-Names/traversal/..::..::;'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by day1player** [comment]
@bkoprivica when using `git clone` you will recieve that error due to how Windows handles those file names. You can install seclists as described above with the `cinst` command which will install our SecLists package and you should not see any errors.
